In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('SPECTF_test.csv')

In [3]:
# print(data)
y=data.iloc[:,44].values
list=[]
for i in range(44):
    list.append(i)
x=data.iloc[:,list].values
print(x)

y=y.tolist()

classA=[]
classB=[]
for i in range(len(y)):

    if y[i]=='Yes':
        classA.append(x[i])
    else:
        classB.append(x[i])
classA=np.array(classA)
classB=np.array(classB)
classA=classA.tolist()
classB=classB.tolist()
K=2

max_iter=100

    


[[32 41 76 ...  8 18 11]
 [76 65 60 ... 30 24 21]
 [60 51 75 ... 31 46 30]
 ...
 [67 64 73 ... 80 67 68]
 [68 65 72 ... 56 58 44]
 [66 54 69 ... 68 59 59]]


In [4]:
def euclidean_dis(point1, point2):
    dis = sum((point1 - point2)**2)**0.5
    return dis

In [5]:
def KMean(data):

    centroids = {}

    for i in range(K):
        centroids[i] = data[i]
    print(centroids)

 
    r=0
    
    
    for i in range(max_iter):
        r=r+1
        classes={}
        for key in range(K):
            classes[key]=[]
        for datapoint in data:
#             print(datapoint)
            distance=[]
            for j in range(K):
               
                dis=euclidean_dis(datapoint,centroids[j])
               
                distance.append(dis)
            mindis=min(distance)
            
            index=distance.index(mindis)
            classes[index].append(datapoint)
            old_centroid=dict(centroids)
            
        for t in range(K):
            class_=classes[t]
                
                
            new_centroid=np.mean(class_,axis=0)
            centroids[t]=new_centroid
        flg=1
        for t in range(K):
             
            a=centroids[t]
            b=old_centroid[t]
            if np.sum((a - b)/b * 100) > 0.001:
                flg = 0
                
            
            
        if flg==1:
            break
    
    
    return classes,centroids
                    

In [6]:
classes,centroids=KMean(x)
for i in range(0,K):
    classes[i]=np.array(classes[i])
    classes[i]=classes[i].tolist()

print("Final centroids are:")
print(centroids)

{0: array([32, 41, 76, 34, 65, 53, 30, 54, 16, 51, 61, 43, 74, 70, 62, 21, 34,
       42, 61, 37, 58, 66, 54, 49, 17, 19, 11, 42, 53, 30, 71,  9, 61, 16,
       31, 43, 67, 61, 29, 31, 17,  8, 18, 11]), 1: array([76, 65, 60, 40, 32, 34, 65, 50, 53, 37, 66, 53, 33, 31, 30, 30, 69,
       75, 64, 45, 68, 65, 57, 43, 23, 23, 53, 77, 48, 32, 55, 32, 48, 23,
       62, 51, 65, 59, 43, 39, 35, 30, 24, 21])}
Final centroids are:
{0: array([66.33333333, 63.33333333, 63.        , 53.16666667, 58.83333333,
       58.        , 64.16666667, 63.66666667, 42.        , 45.        ,
       55.83333333, 52.66666667, 51.        , 53.        , 43.5       ,
       34.5       , 54.83333333, 56.5       , 53.16666667, 42.33333333,
       68.5       , 66.5       , 57.66666667, 57.5       , 28.5       ,
       33.16666667, 40.33333333, 53.83333333, 46.66666667, 38.16666667,
       59.66666667, 48.16666667, 58.66666667, 48.66666667, 52.5       ,
       47.16666667, 55.        , 47.66666667, 46.16666667, 44.8333

In [7]:
def subset(array1,array2):
#     print(array1)
    flg=0
    for i in range(len(array1)):
        if(array2==array1[i]):
            flg=1
            break
    if(flg==1):
        return True
    else:
        return False

In [8]:
def report(cm):
    TP=cm[0][0]
    TN=cm[1][1]
    FN=cm[0][1]
    FP=cm[1][0]
    accuracy=(TP+TN)/(TP+TN+FN+FP)
    recall=(TP)/(TP+FN)
    precision=(TP)/(TP+FP)
    f1_score=(2*recall*precision)/(recall+precision)
    
    print("Accuracy of the model is {}".format(accuracy*100))
    print("Recall of the model is {}".format(recall*100))
    print("Precision of the model is {}".format(precision*100))
    print("F1-Score of the model is {}".format(f1_score*100))

In [9]:

cm=[[0 for i in range(2)] for j in range(2)]


for element in classA:
    
    
    if subset(classes[0],element):
        cm[0][0]=cm[0][0]+1
    elif subset(classes[1],element):
        cm[0][1]=cm[0][1]+1
    
        

for element in classB:

    if subset(classes[0],element):
        cm[1][0]=cm[1][0]+1
    elif subset(classes[1],element):
        cm[1][1]=cm[1][1]+1
print("Confusion Matrix is:")
print(cm)
report(cm)
    

Confusion Matrix is:
[[6, 49], [0, 55]]
Accuracy of the model is 55.45454545454545
Recall of the model is 10.909090909090908
Precision of the model is 100.0
F1-Score of the model is 19.672131147540984
